### PR TITLE
Fixes issue with not properly removing description if not defined

### LINKED ISSUE #419: Description is null in the Generated Experiment if Not Specified in Test

### PR DESCRIPTION
**Pull request by jeppe-style**
fixes https://github.com/benchflow/benchflow/issues/419

depends on PR https://github.com/benchflow/benchflow/pull/443

### CODE REVIEW

**Review by VincenzoFerme — COMMENTED** [review]
The PR has a commit from another PR: https://github.com/benchflow/benchflow/pull/455/commits/2d36e7fcb9057db3ed984317d12bfa80fe417a5d

Maybe the issue is that you force pushed https://github.com/benchflow/benchflow/issues/419

I Reviewed it, when finalised we need to clean it up before merging.

**Comment by jeppe-style** [comment]
don't you have to rebase when it is on top of another PR? Or is that automatic when the previous PR is approved?

**Comment by VincenzoFerme** [comment]
@jeppe-style I had to perform an interactive rebase to remove the commit that was wrongly in this pull as well, and then force push the branch. Check if you find everything you expect in this pull request, and if yes I proceed in the same way for the other ones. For the future (and it should go into the docs), if we need to force push a branch, we do not have to depend on it from other branches.

**Comment by jeppe-style** [comment]
@VincenzoFerme everything is there

**Review by VincenzoFerme — APPROVED** [review]

**Pull request merged**
