### PR TITLE
Adds links to response objects

### LINKED ISSUE #446: Add links in REST API response objects
**Experiment Status**
Experiment Model
- [x] link to experiment bundle for driver-maker on minio (`driverMakerExperimentBundle: URL`)

Trial Model
- [x] link to faban run status (`fabanRunStatus: URL`)

Related to https://github.com/benchflow/benchflow/issues/128

### PR DESCRIPTION
**Pull request by jeppe-style**
as per title

fixes https://github.com/benchflow/benchflow/issues/446

### CODE REVIEW

**Comment by jeppe-style** [comment]
`fabanRunStatus` has double `http://http://` when deployed

**Comment by VincenzoFerme** [comment]
@jeppe-style see https://github.com/benchflow/benchflow/pull/469#pullrequestreview-48854132

**Comment by VincenzoFerme** [comment]
@jeppe-style can you solve the TODO?

**Comment by VincenzoFerme** [comment]
What is left in this PR, is documented in #128 for future improvement.

**Review by VincenzoFerme — APPROVED** [review]

**Pull request merged**
