### PR TITLE
Adds project for common minio client

### PR DESCRIPTION
**Pull request by jeppe-style**
@VincenzoFerme can you please check if we need the `maven-shade-plugin`. Right now it is commented in the `pom.xml`.

The project does not contain any devops related configurations at the moment.

### CODE REVIEW

**Comment by VincenzoFerme** [comment]
@jeppe-style the `maven-shade-plugin` is needed to create a fat jar and solve all the possible dependencies conflicts so that we have the application and its dependencies in a single jar.

**Comment by jeppe-style** [comment]
@VincenzoFerme ok - so we should always include that in all projects?

**Comment by jeppe-style** [comment]
Reminder to also add the method as described in this issue https://github.com/benchflow/benchflow/issues/245

**Review by igormoreno — APPROVED** [review]

**Comment by igormoreno** [comment]
This pull request got too big. We need to merge it and follow up with other requests.

Related issues:
- #245 
- #259 
- #262 
- #263 
- #264

**Pull request merged**
